photozero/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

import timeline.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', timeline.views.photo_list, name='list'),
    url(r'^timeline/', include('timeline.urls', namespace='timeline')),
    url(r'^accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timeline/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	photo_list,
	photo_create,
	photo_detail,
	photo_update,
	photo_delete,
	)

urlpatterns = [
    url(r'^$', photo_list, name='list'),
    url(r'^create/$', photo_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', photo_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', photo_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', photo_delete, name='delete'),
    # url(r'^(?P<slug>[\w-]+)/comment/$', photo_comment, name='comment'),

    # url(r'^post/(?P<pk>[0-9]+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
]

timeline/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.utils import timezone

from allauth.account.models import EmailAddress
from allauth.socialaccount.models import SocialAccount

from imagekit.models import ProcessedImageField
from imagekit.processors import Transpose, ResizeToFit

from django.utils.text import slugify

import hashlib


def upload_location(instance, filename):
	return "%s/%s" %(instance.slug, filename)


class Photo(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	title = models.CharField(max_length=120)
	slug = models.SlugField(unique=True)
	image = ProcessedImageField(upload_to=upload_location, 
		null=True, 
		blank=False,
		processors=[Transpose(), ResizeToFit(1000, 1000, False)],
		format='JPEG',
		options={'quality': 50},
		width_field="width_field",
		height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	description = models.TextField(max_length=1000)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("timeline:detail", kwargs={"slug": self.slug})

	class Meta:
		ordering = ["-timestamp", "-updated"]


def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Photo.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Photo)


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    about_me = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return "{}'s profile".format(self.user.username)

    def __str__(self):
        return "{}'s profile".format(self.user.username)

    class Meta:
        db_table = 'user_profile'

    def profile_image_url(self):
        fb_uid = SocialAccount.objects.filter(user_id=self.user.id, provider='facebook')

        if len(fb_uid):
            return "http://graph.facebook.com/{}/picture?width=40&height=40".format(fb_uid[0].uid)

        return "http://www.gravatar.com/avatar/{}?s=40".format(
            hashlib.md5(self.user.email).hexdigest())


User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class Comment(models.Model):
    post = models.ForeignKey('timeline.Photo', related_name='comments')
    author = models.ForeignKey(User, related_name='comment_set')
    text = models.TextField(max_length=1000)
    created_date = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return self.text

    def __str__(self):
        return self.text

timeline/forms.py
from django import forms
from django.template.defaultfilters import filesizeformat
from .models import Photo, Comment


class PhotoForm(forms.ModelForm):

    def clean(self):
        #first, run the built-in clean. cleaned_data is a dictionary of all of the stuff in the form
        cleaned_data = super(PhotoForm, self).clean()

        #check and see if we have image in our data dictionary (ie, if there is a dictionary key called 'image')
        if 'image' in cleaned_data:
            #reject the upload if the file is too large (size is in bytes, this magic number = 2.5MB)
            if cleaned_data['image']._size > 2621440:
                raise forms.ValidationError('Please keep files under %s. Your file is %s.' % (filesizeformat(2621440), filesizeformat(cleaned_data['image']._size)))

        #always return the cleaned_data dictionary
        return cleaned_data
        
    class Meta:
        model = Photo
        fields = [
            "title",
            "description",
            "image",
        ]


class CommentForm(forms.ModelForm):
	text = forms.CharField(widget=forms.Textarea, label='Leave a comment: ')
	class Meta:
		model = Comment
		fields = [
			"text",
		]


# 2.5MB - 2621440
# 5MB - 5242880
# 10MB - 10485760
# 20MB - 20971520
# 50MB - 5242880
# 100MB 104857600
# 250MB - 214958080
# 500MB - 429916160

timeline/views.py
from urllib import quote_plus
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import PhotoForm, CommentForm
from .models import Photo, Comment

# def index(request):
# 	return HttpResponse('Hello David!')

def photo_create(request):
	if not request.user.is_authenticated():
	 	return HttpResponseRedirect("/accounts/login")

	form = PhotoForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		messages.success(request, "Succesfully Created") # message success
		return HttpResponseRedirect(instance.get_absolute_url())
		
	context = {
		"form": form,
	}

	return render(request, "photo_upload.html", context)


def photo_detail(request, slug=None): # retrieve
	if not request.user.is_authenticated():
		return HttpResponseRedirect("/accounts/login")

	instance = get_object_or_404(Photo, slug=slug)

	if request.method == "POST":
		form = CommentForm(request.POST)
		if form.is_valid():
		    comment = form.save(commit=False)
		    comment.author = request.user
		    comment.post = instance
		    comment.save()
		    return redirect('timeline:detail', slug=instance.slug)
	else:
		form = CommentForm()

	share_string = quote_plus(instance.description)

	context = {
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
		"form": form,
	}

	return render(request, "photo_detail.html", context)   


def photo_list(request): # list items
	queryset_list = Photo.objects.all()
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Photo.objects.all()

	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
			Q(title__icontains=query) |
			Q(description__icontains=query) |
			Q(user__first_name__icontains=query) |
			Q(user__last_name__icontains=query)
			).distinct()

	paginator = Paginator(queryset_list, 10) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
	    # If page is not an integer, deliver first page.
	    queryset = paginator.page(1)
	except EmptyPage:
	    # If page is out of range (e.g. 9999), deliver last page of results.
	    queryset = paginator.page(paginator.num_pages)

	context = {
		"object_list": queryset,
		"title": "PhotoZone",
		"page_request_var": page_request_var,
	}

	return render(request, "photo_list.html", context)


def photo_update(request, slug=None):
	if not request.user.is_authenticated():
		return HttpResponseRedirect("/accounts/login")
	instance = get_object_or_404(Photo, slug=slug)
	form = PhotoForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "Succesfully Updated") # message success

		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}

	return render(request, "photo_update.html", context)


def photo_delete(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser or not request.user.is_authenticated():
		return HttpResponseRedirect("/accounts/login")
	instance = get_object_or_404(Photo, slug=slug)
	instance.delete()
	messages.success(request, "Succesfully Deleted")
	return redirect("timeline:list")

timeline/templates/408.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
 
{% block title %}Page Requested Timeout{% endblock %}
 
{% block content %}

  	<div class="container">
		<div class="col-md-6 col-md-offset-3 text-center">
		  <div class="row">
			  	<h1>Page requested timeout. 408 Error</h1>
	 			<p>Sorry, but the requested page has timed out please refresh and try again.</p>
			</div>
		</div>
	</div>

{% endblock %}

timeline/templates/media_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load staticfiles %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}

  <div id="header" class="text-center">
      <img src="{% static 'img/logo.png' %}" />
      <h3>PhotoZero</h3>

      <div class="space"></div> <!-- 40px Vertical Spacing -->

      <p>Share your photographs.</p>
      <button href="{% url 'timeline:create' %}" class="btn btn-purple">Upload</button>      
  </div>

  <div class="space"></div> <!-- 40px Vertical Spacing -->

  <!-- Photo Detail -->
 	<section id="photoDetail">

	<div class="container-fluid">
		<div class="row">
			<div class="photoDetail">
			{% if instance.image %}
	    		<img src='{{ instance.image.url }}' class='img-responsive' />
	    	{% endif %}
    		</div>
    	</div>
	</div>

	<div class="container"> <!-- Container -->
	 	<div class="row">
			<div class="col-md-8">
				<h1>{{ title }} <small>{% if instance.draft %}<span style='color:red;'>Draft</span> {% endif %}{{ instance.publish }}</small></h1>
			</div>
			<div class="col-md-4" style="padding: 20px 15px 0 15px !important;">
						
				{% if instance.user.get_full_name %}
				<a class="btn btn-block btn-lg btn-purplea" style="cursor: default; text-transform: none;">
				Author: {{ instance.user.get_full_name }}
				</a>
				{% else %}
				<a class="btn btn-block btn-lg btn-purplea" style="cursor: default; text-transform: none;">
				Author: {{ instance.user }}
				</a>
				{% endif %}

			</div>
		</div>
	
		<div class="row">
			<div class="col-sm-12">
				<p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
				</p>
			</div>
		</div>	
		
		<div class='row'>
			<div class='col-sm-12'>
				<div class="description">
					{{ instance.content|linebreaks }}
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-5">
				<a href="{% url 'timeline:list' %}" class="btn btn-block btn-lg btn-dark" role="button"><i class="fa fa-angle-double-left"></i>
 Back to Timeline</a>
			</div>
			<div class="col-sm-5">
				<a href="{% url 'timeline:update' slug=instance.slug %}" class="btn btn-block btn-lg btn-purple" role="button"><i class="fa fa-pencil-square-o"></i>
 Edit</a>
			</div>
			<div class="col-sm-2">
				<a href="{% url 'timeline:delete' slug=instance.slug %}" class="btn btn-block btn-lg btn-red" role="button"><i class="fa fa-times-circle"></i>
 Delete</a>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">
				<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5" data-width="100%"></div>
			</div>
		</div>

	</div>

  </section>


{% endblock content %}

timeline/templates/media_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>Form</h1>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form | crispy }}
<br/>
<input type='submit' class='btn btn-block btn-lg btn-dark' value='Create' />
</form>
</div>
{% endblock content %}

timeline/templates/media_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

  <div id="header" class="text-center">
      <img src="{% static 'img/logo.png' %}" />
      <h3>PhotoZero</h3>

      <div class="space"></div> <!-- 40px Vertical Spacing -->

      <p>Share your photographs.</p>
      <a href="{% url 'timeline:create' %}" class="btn btn-purple"><i class="fa fa-upload"></i>
 Upload</a>

      <div class="space"></div> <!-- 40px Vertical Spacing -->
      
      <form method="GET" action="" class="form-inline">
        <div class="form-group">
          <input type="text" placeholder="&#xF002;" style="font-family:Arial, FontAwesome" name="q" class="form-control input-lg" value="{{ request.GET.q }}">
          <!-- <button type="submit" class="btn btn-purple searchBtn"><i class="fa fa-search"></i></button> -->
        </div>      
      </form>
  </div>

  <div class="space"></div> <!-- 40px Vertical Spacing -->

  <!-- Timeline -->
  <section id="timeline">

  <div class="container-fluid"> <!-- Container Fluid-->
  {% for obj in object_list %}
    <div class="row">
        <div class="timeline">
            {% if obj.image %}
             <img src='{{ obj.image.url }}' class='img-responsive' />
            {% endif %}
        </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-12 text-left">
                    <div class="fb-like pull-left" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
          <p class="pull-right"><small>Posted {{ obj.timestamp | timesince }} ago</small></p>
        </div>
      </div>

      <div class="row">
        <div class="col-md-3">
          <a class="btn btn-block btn-lg btn-purplea" style="cursor: default; text-transform: none;">{{ obj.title }}</a>
        </div>
        <div class="col-md-7">
          {% if obj.user.get_full_name %}
          <a class="btn btn-block btn-lg btn-purplea" style="cursor: default; text-transform: none;">Photographer: {{ obj.user.get_full_name }}</a>
          {% else %}
          <a class="btn btn-block btn-lg btn-purplea" style="cursor: default; text-transform: none;">Photographer: {{ obj.user }}</a>
          {% endif %}
        </div>
        <div class="col-md-2">
          <a href="{{ obj.get_absolute_url }}" class="btn btn-block btn-lg btn-dark" role="button">View <i class="fa fa-angle-double-right"></i>
</a>
        </div>
      </div>
    </div>
          <!-- <a class="btn btn-block btn-lg btn-purplea" style="cursor: default; text-transform: none;">
            {{ obj.content|truncatechars:50 }}
          </a> -->
    <hr/>
    <div class="space"></div> <!-- 40px Vertical Spacing -->
  {% endfor %}
  </div>

  </section>

  <div class="space"></div> <!-- 40px Vertical Spacing -->

  <div class="container">
    <div class="col-md-12 text-center">
      <ul class="pagination pagination-lg">
        <li>{% if object_list.has_previous %}
          <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a>
          {% endif %}
        </li>
        <li>
          <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
          </span>
        </li>
        <li>
          <a href="#">2</a>
        </li>
        <li>{% if object_list.has_next %}
          <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&raquo;</a>
            {% endif %}
        </li>
      </ul>
    </div>
  </div>

{% endblock content %}

timeline/templates/photo_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% load i18n %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}

  <div class="text-center">
      <a href="{% url 'timeline:create' %}" class="btn btn-purple"><i class="fa fa-upload"></i> Upload</a>      
  </div>

  <div class="space"></div> <!-- 40px Vertical Spacing -->

  <!-- Photo Detail -->
 	<section id="photoDetail">

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="photoDetail">
				{% if instance.image %}
		    		<img src='{{ instance.image.url }}' class='img-responsive' />
		    	{% endif %}
	    		</div>
    		</div>
    	</div>
	</div>

	<div class="container"> <!-- Container -->

		<div class="row">
	        <div class="col-md-12">
	          <div class="fb-like pull-left" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
	        </div>
	      </div>

	 	<div class="row">

			<div class="col-md-7">	
				<a class="btn btn-block btn-lg btn-purplea" style="cursor: default; text-transform: none;">
				Photographer: {{ instance.user }}
				</a>
			</div>

			<div class="col-md-5 text-right">
					<span class="btn btn-lg btn-purplea" style="cursor: default; text-transform: none;">Share</span>
				<!-- Comments section -->
					<a class="btn btn-lg btn-graya btn--comment" href="#comments" data-toggle="tooltip" data-placement="bottom" title="Comments" data-original-title="Comments">
					    <span><i class="fa fa-comment" style="color: #FF9B37;"></i></span>
					</a>

				<!-- Facebook -->
				<a class="btn btn-lg btn-darka btn--facebook" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" onclick="window.open(this.href,'facebook-share-dialog','width=626,height=436');return false;" data-toggle="tooltip" data-placement="bottom" title="Facebook" data-original-title="Facebook">
				    <span><i class="fa fa-facebook-square" style="color: #004088;"></i></span>
				</a>

				<!-- Twitter -->
				<a class="btn btn-lg btn-darka btn--twitter" target="_blank" href="https://twitter.com/home?status={{ share_string }}%20{{ request.build_absolute_uri }}" onclick="window.open(this.href,'twitter-share-dialog','width=626,height=436');return false;" data-toggle="tooltip" data-placement="bottom" title="Twitter" data-original-title="Twitter">
				   <span><i class="fa fa-twitter-square" style="color: #49A8DE;"></i></span>
				</a>

				<!-- WhatsApp -->
				<a class="btn btn-lg btn-darka btn--whatsapp hidden-md-plus" href="whatsapp://send?text={{ title }}%20{{ request.build_absolute_uri }}" target="_blank" data-text="{{ title }} " data-href="{{ request.build_absolute_uri }}" data-toggle="tooltip" data-placement="bottom" title="WhatsApp" data-original-title="WhatsApp"><span><i class="fa fa-whatsapp" style="color: #43D854;"></i></span></a>

			</div>
		</div>
	
		<div class="row">
			<div class="col-sm-12">
				<h1>{{ title }}</h4>
				<small>{{ instance.timestamp }}  ({{ instance.timestamp | timesince }} Ago)</small>
			</div>
		</div>	
		
		<div class='row'>
			<div class='col-sm-12'>

				<div class="description">
					<h4>Description</h4>
					{{ instance.description|linebreaks }}
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-2">
				<a href="{% url 'timeline:list' %}" class="btn btn-block btn-lg btn-dark" role="button"><i class="fa fa-angle-double-left"></i>
 Back</a>
			</div>
			<div class="col-sm-4">
				<a href="{{ instance.image.url }}" class="btn btn-block btn-lg btn-purple" role="button"><i class="fa fa-download"></i> Download</a>
			</div>
			{% if user.is_superuser or request.user == instance.user %}  
			<div class="col-sm-4">
				<a href="{% url 'timeline:update' slug=instance.slug %}" class="btn btn-block btn-lg btn-purple" role="button"><i class="fa fa-pencil-square-o"></i> Edit</a>
			</div> 
			<div class="col-sm-2">	  
				<a href="{% url 'timeline:delete' slug=instance.slug %}" class="btn btn-block btn-lg btn-red" role="button"><i class="fa fa-times-circle"></i> Delete</a>
			</div>
			{% else %}
			<div class="col-sm-4">
			</div> 
			<div class="col-sm-2">	  
			</div>			
			{% endif %}

		</div>

		<div class="space"></div> <!-- 40px Vertical Spacing -->
	
		<div class="comment-section">
		<div class="row">
			<div class="col-md-12" id="comments">
				<h4>
					{% if instance.comments.count == 0 %}
		            No Comments
		            {% elif instance.comments.count == 1 %}
		            {{ instance.comments.count }} Comment
		            {% else %}
		            {{ instance.comments.count }} Comments
		            {% endif %}
				</h4>
				<hr style="margin-top: 10px;">
					{% for comment in instance.comments.all %}
					    <div class="comment">
					        <div class="date pull-right">{{ comment.created_date | timesince }} Ago</div>
					        <strong>{{ comment.author }}</strong>
					        <p>{{ comment.text|linebreaks }}</p>
					    </div>
					    <hr>
					{% endfor %}
				<!-- Facebook comments -->
				<!--<div class="col-sm-12">
					<div id="comments" class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5" data-width="100%"></div>
				</div> -->
			</div>
		</div>
		
		{% if user.is_superuser or user.is_authenticated %} 
		<div class="row">
			<div class="col-md-12">
				<form method="POST" class="comment-form" action=''>
					{% csrf_token %}
			        {{ form | crispy }}
				    <button type="submit" class="comment-add btn btn-lg btn-purple">Add</button>
				</form>
			</div>
		</div>
		{% endif %}
	</div>

  </section>


{% endblock content %}

timeline/templates/photo_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% load i18n %}

{% block content %}

  <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="text-center">
              {% if user.is_superuser or user.is_authenticated %}  
              <a href="{% url 'timeline:create' %}" class="btn btn-purple"><i class="fa fa-upload"></i> Upload</a>
              {% else %}
              <a href="{% url 'account_login' %}" class="btn btn-purple"><i class="fa fa-sign-in"></i> Login</a>
              <p>or</p>
              <a href="{% url 'account_signup' %}" class="btn btn-purple"><i class="fa fa-pencil-square-o"></i> Signup</a>
              {% endif %}

              <div class="space"></div> <!-- 40px Vertical Spacing -->
              
              <form method="GET" action="" class="form-inline">
                <div class="form-group">
                  <input type="text" placeholder="&#xF002; Search Photos" style="font-family:Arial, FontAwesome" name="q" class="form-control input-lg" value="{{ request.GET.q }}"><br/>
                  <a href="{% url 'timeline:list' %}">Clear search results</a>
                  <!-- <button type="submit" class="btn btn-purple searchBtn"><i class="fa fa-search"></i></button> -->
                </div>      
              </form>
          </div>
      </div>
    </div>
  </div>

  <!-- Timeline -->
  <section id="timeline">

  {% for obj in object_list %}
  <div class="space"></div> <!-- 40px Vertical Spacing -->
  <div class="container"> <!-- Container Fluid-->

    <div class="row">
      <div class="col-md-12">
        <h3>{{ obj.title }}</h3>
        <h5>{{ obj.timestamp }}</h5>
      </div>
    </div>
  
    <div class="row">
      <div class="col-md-12">
        <div class="timeline">
            {% if obj.image %}
             <img src='{{ obj.image.url }}' class='img-responsive' />
            {% endif %}
        </div>
      </div>
    </div>
  </div>

    <div class="container">
<!--       {% if user.is_authenticated %}
      <div class="row">
        <div class="col-md-12">
          <div class="fb-like pull-left" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
        </div>
      </div>
      {% endif %} -->

      <div class="row">
        <div class="col-md-4">
          <a class="btn btn-block btn-lg btn-purplea" style="cursor: default; text-transform: none;">
            {% if obj.comments.count == 0 %}
            No Comments
            {% elif obj.comments.count == 1 %}
            {{ obj.comments.count }} Comment
            {% else %}
            {{ obj.comments.count }} Comments
            {% endif %}
          </a>
        </div>
        <div class="col-md-6">
          <a class="btn btn-block btn-lg btn-purplea" style="cursor: default; text-transform: none;">Photographer: {{ obj.user }}</a>
        </div>
        <div class="col-md-2">
          <a href="{{ obj.get_absolute_url }}" class="btn btn-block btn-lg btn-dark" role="button">View <i class="fa fa-angle-double-right"></i></a>
        </div>
      </div>
    </div>
          <!-- <a class="btn btn-block btn-lg btn-purplea" style="cursor: default; text-transform: none;">
            {{ obj.content|truncatechars:50 }}
          </a> -->
    <div class="space"></div> <!-- 40px Vertical Spacing -->
  {% endfor %}
  </div>

  </section>

  <div class="space"></div> <!-- 40px Vertical Spacing -->

  <div class="container">
    <div class="col-md-12 text-center">
      <ul class="pagination pagination-lg">
        <li>{% if object_list.has_previous %}
          <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a>
          {% endif %}
        </li>
        <li>
          <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
          </span>
        </li>
        <li>
          <a href="#">2</a>
        </li>
        <li>{% if object_list.has_next %}
          <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&raquo;</a>
            {% endif %}
        </li>
      </ul>
    </div>
  </div>

{% endblock content %}